[package]
name = "metabodecon-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "metabodecon_python"
crate-type = ["cdylib"]

[dependencies]
metabodecon = { path = "../metabodecon" }
numpy = "0.23.0"
pyo3 = { version = "0.23.2", features = ["extension-module"] }
