[package]
name = "metabodecon"
version = "0.1.0"
edition = "2021"

[features]
default = ["parallel"]
parallel = ["rayon"]

[dependencies]
byteorder = "1.5.0"
num-traits = "0.2.19"
regex = "1.11.1"
hdf5 = "0.8.1"
rayon = { version = "1.10.0", optional = true }

[dev-dependencies]
assert_approx_eq = "1.1.0"
criterion = "0.5.1"

[lints]
workspace = true

[[bench]]
name = "deconvoluter"
harness = false
