[package]
name = "metabodecon"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.19"
hdf5 = "0.8.1"

[dev-dependencies]
assert_approx_eq = "1.1.0"
criterion = "0.5.1"

[[bench]]
name = "deconvoluter"
harness = false
