name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [ stable, beta, nightly ]

    steps:
      - uses: actions/checkout@v4

      - name: Install HDF5
        run: sudo apt-get update && sudo apt-get install -y libhdf5-dev

      - name: Set up Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Run tests
        run: cargo test --verbose

  benchmark:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [ stable, beta, nightly ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install HDF5
        run: sudo apt-get update && sudo apt-get install -y libhdf5-dev

      - name: Set up Rust
        run: rustup update stable && rustup default stable

      - name: Checkout state before the push
        run: git checkout ${{ github.event.before }}

      - name: Run benchmarks before the push
        run: cargo bench --profile release --verbose

      - name: Checkout state after the push
        run: git checkout ${{ github.sha }}

      - name: Run benchmarks after the push
        run: cargo bench --profile release --verbose

      - name: Upload benchmark reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: criterion-report
          path: target/criterion/
